from PINNmizer.diagnostics._legacy_impl import make_fixed_pde_batch, make_fixed_pde_batch_from_csv, compute_fixed_diagnostics
__all__=["make_fixed_pde_batch","make_fixed_pde_batch_from_csv","compute_fixed_diagnostics"]
