"""Canonical truth normalisation and deterministic state-grid alignment."""
from __future__ import annotations

import re
import time
import traceback
from pathlib import Path
from typing import Mapping

import numpy as np
import pandas as pd

STANDARD_COLUMNS = ["time", "species_idx", "species", "w", "x", "N", "log_N", "log10_N"]
REPO_ROOT = Path(__file__).resolve().parents[2]
SINGLE_SPECIES_TRUTH = REPO_ROOT / "single_species_projection_long.csv"
MULTISPECIES_TRUTH = REPO_ROOT / "mizer_projection_long.csv"
SINGLE_SPECIES_INDEX = {"N.pout": 3, "Sole": 7, "Cod": 11}


def truth_source_for_task(task_id: int) -> Path:
    """Return the authoritative mizer projection for a final-suite task.

    Tasks 0-11 are the independent single-species simulations generated by
    ``final_runs/single_species.R``. Tasks 12-69 use the common multispecies
    mizer projection. These sources are deliberately repository-root files,
    not files copied from HPC run directories.
    """
    task_id = int(task_id)
    if not 0 <= task_id <= 69:
        raise ValueError(f"Unknown final-suite task id: {task_id}")
    return SINGLE_SPECIES_TRUTH if task_id <= 11 else MULTISPECIES_TRUTH


def find_truth_source(project_root: Path | None = None) -> Path | None:
    """Backward-compatible multispecies truth lookup."""
    del project_root
    return MULTISPECIES_TRUTH if MULTISPECIES_TRUTH.is_file() else None


def normalise_state(df: pd.DataFrame, source: str = "state") -> pd.DataFrame:
    aliases = {"t": "time", "t_eval": "time", "sp": "species", "weight": "w", "w_eval": "w", "x_eval": "x", "n": "N", "logN": "log_N", "log10N": "log10_N"}
    out = df.rename(columns={column: aliases.get(column, column) for column in df.columns}).copy()
    if "time" not in out or not ({"w", "x"} & set(out)) or not ({"N", "log_N", "log10_N"} & set(out)):
        raise ValueError(f"{source} needs time, w or x, and N/log_N/log10_N")
    if "species_idx" not in out:
        if "species" in out:
            labels = out["species"].astype(str)
            parsed = labels.str.extract(r"(?:^|_)sp(?:ecies)?_?(\d+)$", flags=re.IGNORECASE)[0]
            if parsed.notna().all():
                out["species_idx"] = pd.to_numeric(parsed)
            else:
                names = list(pd.unique(labels))
                out["species_idx"] = labels.map({name: i for i, name in enumerate(names)})
        else:
            out["species_idx"] = 0
    if "species" not in out:
        out["species"] = out["species_idx"].map(lambda value: f"species_{int(value)}")
    for column in ("time", "species_idx", "w", "x", "N", "log_N", "log10_N"):
        if column in out:
            out[column] = pd.to_numeric(out[column], errors="coerce")
    if "w" not in out:
        out["w"] = np.exp(out["x"])
    if "x" not in out:
        out["x"] = np.log(out["w"].where(out["w"] > 0))
    if "N" not in out:
        out["N"] = np.exp(out["log_N"]) if "log_N" in out else np.power(10.0, out["log10_N"])
    out = out[np.isfinite(out["time"]) & np.isfinite(out["x"]) & np.isfinite(out["N"]) & (out["N"] > 0)].copy()
    out["log_N"] = np.log(out["N"])
    out["log10_N"] = np.log10(out["N"])
    return out[STANDARD_COLUMNS].sort_values(["species_idx", "time", "x"]).reset_index(drop=True)


def load_truth_state(path: str | Path) -> pd.DataFrame:
    path = Path(path)
    if path.suffix.lower() != ".csv":
        raise ValueError("The truth source currently supports long-form CSV only")
    raw = pd.read_csv(path)
    if path.name == "single_species_projection_long.csv" and "species_idx" not in raw:
        if "species" not in raw:
            raise ValueError("single_species_projection_long.csv requires a species column")
        names = set(raw["species"].astype(str).unique())
        unknown = names.difference(SINGLE_SPECIES_INDEX)
        if unknown:
            raise ValueError(f"Unexpected species in single-species truth: {sorted(unknown)}")
        raw["species_idx"] = raw["species"].astype(str).map(SINGLE_SPECIES_INDEX)
    return normalise_state(raw, str(path))


def align_states(prediction: pd.DataFrame, truth: pd.DataFrame, *, w_max: Mapping[int, float] | None = None) -> tuple[pd.DataFrame, dict[str, object]]:
    """Place truth on prediction cells using linear interpolation in time then x.

    Exact time/x values are naturally preserved by ``numpy.interp``. Values
    outside truth support are NaN (never extrapolated). Both states are first
    restricted to positive abundance and species-specific active weights.

    Interpolation is vectorised over the target grid: first all target x values
    are interpolated at each truth time, then all target times are interpolated
    for each target x. This is mathematically equivalent to the previous
    per-cell implementation but avoids repeated DataFrame filtering/grouping.
    """
    started = time.perf_counter()
    print("[state.align] start", flush=True)
    try:
        pred, true = normalise_state(prediction, "prediction"), normalise_state(truth, "truth")
        print(
            f"[state.align] normalised prediction_rows={len(pred)} truth_rows={len(true)} "
            f"prediction_species={pred.species_idx.nunique()} truth_species={true.species_idx.nunique()}",
            flush=True,
        )

        w_max = dict(w_max or {})
        if w_max:
            pred = pred[pred.apply(lambda row: row.w <= w_max.get(int(row.species_idx), np.inf), axis=1)]
            true = true[true.apply(lambda row: row.w <= w_max.get(int(row.species_idx), np.inf), axis=1)]
            print(f"[state.align] active-weight mask prediction_rows={len(pred)} truth_rows={len(true)}", flush=True)

        aligned_parts: list[pd.DataFrame] = []
        exact_time, interpolated_time = 0, 0

        for species_idx, targets in pred.groupby("species_idx", sort=False):
            source = true[true.species_idx == species_idx]
            print(
                f"[state.align] species={int(species_idx)} target_rows={len(targets)} source_rows={len(source)}",
                flush=True,
            )
            if source.empty:
                continue

            source_times = np.sort(source.time.unique())
            target_times = np.sort(targets.time.unique())
            target_xs = np.sort(targets.x.unique())

            # Stage 1: interpolate in x=log(w) for every requested target x at
            # each truth time. Only one profile/groupby is built per truth time.
            weight_interpolated = np.full((len(source_times), len(target_xs)), np.nan, dtype=float)
            for time_index, source_time in enumerate(source_times):
                profile = (
                    source[np.isclose(source.time, source_time)]
                    .groupby("x", as_index=False)
                    .log10_N.mean()
                    .sort_values("x")
                )
                xs = profile.x.to_numpy()
                ys = profile.log10_N.to_numpy()
                if len(xs):
                    weight_interpolated[time_index] = np.interp(
                        target_xs, xs, ys, left=np.nan, right=np.nan
                    )

            # Stage 2: for each requested target x, interpolate those values in
            # time onto all requested prediction times. Again, never extrapolate.
            truth_grid = np.full((len(target_times), len(target_xs)), np.nan, dtype=float)
            exact_grid = np.zeros((len(target_times), len(target_xs)), dtype=bool)
            for x_index in range(len(target_xs)):
                values = weight_interpolated[:, x_index]
                valid = np.isfinite(values)
                if not valid.any():
                    continue
                valid_times = source_times[valid]
                valid_values = values[valid]
                truth_grid[:, x_index] = np.interp(
                    target_times,
                    valid_times,
                    valid_values,
                    left=np.nan,
                    right=np.nan,
                )
                exact_grid[:, x_index] = np.isclose(
                    target_times[:, None], valid_times[None, :]
                ).any(axis=1)

            time_index = np.searchsorted(target_times, targets.time.to_numpy())
            x_index = np.searchsorted(target_xs, targets.x.to_numpy())
            truth_values = truth_grid[time_index, x_index]
            valid_rows = np.isfinite(truth_values)
            if not valid_rows.any():
                continue

            exact_rows = exact_grid[time_index, x_index] & valid_rows
            exact_time += int(exact_rows.sum())
            interpolated_time += int(valid_rows.sum() - exact_rows.sum())

            part = targets.loc[valid_rows, ["time", "species_idx", "species", "w", "x", "log10_N"]].copy()
            part = part.rename(columns={"log10_N": "pred_log10_N"})
            part["true_log10_N"] = truth_values[valid_rows]
            part["error_log10_N"] = part.pred_log10_N - part.true_log10_N
            aligned_parts.append(part)

        aligned = (
            pd.concat(aligned_parts, ignore_index=True)
            if aligned_parts
            else pd.DataFrame(
                columns=[
                    "time", "species_idx", "species", "w", "x",
                    "pred_log10_N", "true_log10_N", "error_log10_N",
                ]
            )
        )
        metadata = {
            "time_method": "exact where available, otherwise linear interpolation",
            "weight_method": "exact where available, otherwise linear interpolation in x=log(w)",
            "extrapolation": "none",
            "target_grid": "prediction",
            "valid_cells": len(aligned),
            "exact_time_cells": exact_time,
            "interpolated_time_cells": interpolated_time,
            "active_weight_limits": w_max,
        }
        print(
            f"[state.align] done valid_cells={len(aligned)} elapsed_s={time.perf_counter() - started:.3f}",
            flush=True,
        )
        return aligned, metadata
    except Exception:
        print(f"[state.align] FAILED after {time.perf_counter() - started:.3f}s", flush=True)
        traceback.print_exc()
        raise
